// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RickLocalization.Repository;

namespace RickLocalization.Repository.Migrations
{
    [DbContext(typeof(RickLocalizationContext))]
    [Migration("20210723235357_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("RickLocalization.Domain.Dimension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(4)");

                    b.Property<int>("RickId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("DateTime");

                    b.HasKey("Id");

                    b.HasIndex("RickId");

                    b.ToTable("Dimensions");
                });

            modelBuilder.Entity("RickLocalization.Domain.Morty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RickId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RickId")
                        .IsUnique();

                    b.ToTable("Mortys");
                });

            modelBuilder.Entity("RickLocalization.Domain.Rick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("QI")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Ricks");
                });

            modelBuilder.Entity("RickLocalization.Domain.Dimension", b =>
                {
                    b.HasOne("RickLocalization.Domain.Rick", "Rick")
                        .WithMany("Dimensions")
                        .HasForeignKey("RickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RickLocalization.Domain.Morty", b =>
                {
                    b.HasOne("RickLocalization.Domain.Rick", "Rick")
                        .WithOne("Morty")
                        .HasForeignKey("RickLocalization.Domain.Morty", "RickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
